import { writeFile } from "node:fs/promises";
import { CeramicClient } from "@ceramicnetwork/http-client";
import { model as addressBookModel } from "crypto-address-book";
import { ModelManager } from "@glazed/devtools";

const ceramic = new CeramicClient(
  process.env.CERAMIC_URL || "https://ceramic-clay.3boxlabs.com"
);

const manager = new ModelManager({ ceramic });
manager.addJSONModel(addressBookModel);

const aliases = await manager.deploy();
const modelFile = `// This is a file generated by the deploy-model.mjs script, do not edit manually
  
import { ModelTypes } from "crypto-address-book";
import type { ModelTypesToAliases } from '@glazed/types'
  
export const aliases: ModelTypesToAliases<ModelTypes> = ${JSON.stringify(
  aliases
)}
  `;

await writeFile(
  new URL("../src/__generated__/model.ts", import.meta.url),
  modelFile
);
